//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZoneConverter.Contracts
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bartjolling.github.io/", ConfigurationName="TimeZoneConverter.Contracts.ITimeZoneConverter")]
    public interface ITimeZoneConverter
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bartjolling.github.io/ITimeZoneConverter/ConvertToOffsetRequest", ReplyAction="http://bartjolling.github.io/ITimeZoneConverter/ConvertToOffsetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TimeZoneConverter.Contracts.ConvertToOffsetResponse> ConvertToOffsetAsync(TimeZoneConverter.Contracts.ConvertToOffsetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bartjolling.github.io/")]
    public partial class TimeZoneConversionRequest
    {
        
        private System.DateTime fromDateTimeField;
        
        private int fromOffsetField;
        
        private int toOffsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime FromDateTime
        {
            get
            {
                return this.fromDateTimeField;
            }
            set
            {
                this.fromDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FromOffset
        {
            get
            {
                return this.fromOffsetField;
            }
            set
            {
                this.fromOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ToOffset
        {
            get
            {
                return this.toOffsetField;
            }
            set
            {
                this.toOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bartjolling.github.io/")]
    public partial class TimeZoneConversionResponse
    {
        
        private System.DateTime toDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ToDateTime
        {
            get
            {
                return this.toDateTimeField;
            }
            set
            {
                this.toDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertToOffsetRequest", WrapperNamespace="http://bartjolling.github.io/", IsWrapped=true)]
    public partial class ConvertToOffsetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bartjolling.github.io/", Order=0)]
        public TimeZoneConverter.Contracts.TimeZoneConversionRequest TimeZoneConversionRequest;
        
        public ConvertToOffsetRequest()
        {
        }
        
        public ConvertToOffsetRequest(TimeZoneConverter.Contracts.TimeZoneConversionRequest TimeZoneConversionRequest)
        {
            this.TimeZoneConversionRequest = TimeZoneConversionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertToOffsetResponse", WrapperNamespace="http://bartjolling.github.io/", IsWrapped=true)]
    public partial class ConvertToOffsetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bartjolling.github.io/", Order=0)]
        public TimeZoneConverter.Contracts.TimeZoneConversionResponse TimeZoneConversionResponse;
        
        public ConvertToOffsetResponse()
        {
        }
        
        public ConvertToOffsetResponse(TimeZoneConverter.Contracts.TimeZoneConversionResponse TimeZoneConversionResponse)
        {
            this.TimeZoneConversionResponse = TimeZoneConversionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITimeZoneConverterChannel : TimeZoneConverter.Contracts.ITimeZoneConverter, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TimeZoneConverterClient : System.ServiceModel.ClientBase<TimeZoneConverter.Contracts.ITimeZoneConverter>, TimeZoneConverter.Contracts.ITimeZoneConverter
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TimeZoneConverterClient() : 
                base(TimeZoneConverterClient.GetDefaultBinding(), TimeZoneConverterClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITimeZoneConverter.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeZoneConverterClient(EndpointConfiguration endpointConfiguration) : 
                base(TimeZoneConverterClient.GetBindingForEndpoint(endpointConfiguration), TimeZoneConverterClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeZoneConverterClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TimeZoneConverterClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeZoneConverterClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TimeZoneConverterClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeZoneConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeZoneConverter.Contracts.ConvertToOffsetResponse> TimeZoneConverter.Contracts.ITimeZoneConverter.ConvertToOffsetAsync(TimeZoneConverter.Contracts.ConvertToOffsetRequest request)
        {
            return base.Channel.ConvertToOffsetAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeZoneConverter.Contracts.ConvertToOffsetResponse> ConvertToOffsetAsync(TimeZoneConverter.Contracts.TimeZoneConversionRequest TimeZoneConversionRequest)
        {
            TimeZoneConverter.Contracts.ConvertToOffsetRequest inValue = new TimeZoneConverter.Contracts.ConvertToOffsetRequest();
            inValue.TimeZoneConversionRequest = TimeZoneConversionRequest;
            return ((TimeZoneConverter.Contracts.ITimeZoneConverter)(this)).ConvertToOffsetAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITimeZoneConverter))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITimeZoneConverter))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50355/TimeZoneConverter.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TimeZoneConverterClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITimeZoneConverter);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TimeZoneConverterClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITimeZoneConverter);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITimeZoneConverter,
        }
    }
}
