<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="TimeZoneConvertor" targetNamespace="http://thosa.it/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://thosa.it/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl">
	<wsdl:types>
		<xsd:schema targetNamespace="http://thosa.it/Imports">
			<xsd:import schemaLocation="TimeZoneConvertor.xsd" namespace="http://thosa.it/"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ITimeZoneConvertor_ConvertToOffset_InputMessage">
		<wsdl:part name="parameters" element="tns:ConvertToOffsetRequest"/>
	</wsdl:message>
	<wsdl:message name="ITimeZoneConvertor_ConvertToOffset_OutputMessage">
		<wsdl:part name="parameters" element="tns:ConvertToOffsetResponse"/>
	</wsdl:message>
	<wsdl:portType name="ITimeZoneConvertor">
		<wsdl:operation name="ConvertToOffset">
			<wsdl:input wsaw:Action="http://thosa.it/ITimeZoneConvertor/ConvertToOffsetRequest" message="tns:ITimeZoneConvertor_ConvertToOffset_InputMessage"/>
			<wsdl:output wsaw:Action="http://thosa.it/ITimeZoneConvertor/ConvertToOffsetResponse" message="tns:ITimeZoneConvertor_ConvertToOffset_OutputMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BasicHttpBinding_ITimeZoneConvertor" type="tns:ITimeZoneConvertor">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ConvertToOffset">
			<soap:operation soapAction="http://thosa.it/ITimeZoneConvertor/ConvertToOffset" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="TimeZoneConvertor">
		<wsdl:port name="BasicHttpBinding_ITimeZoneConvertor" binding="tns:BasicHttpBinding_ITimeZoneConvertor">
			<soap:address location="http://localhost:50367/TimeZoneConvertor.svc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>